apiVersion: v1
kind: Service
metadata:
  name: csi-snapshot-metadata
  namespace: openshift-cluster-csi-drivers
  labels:
    app.kubernetes.io/name: csi-snapshot-metadata
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: csi-snapshot-metadata-certs
spec:
  ports:
  - name: snapshot-metadata
    port: 6443
    protocol: TCP
    targetPort: 50051
  selector:
    app.kubernetes.io/name: csi-snapshot-metadata
